[profile.default]
solc = '0.8.16'
bytecode_hash = 'none'
optimizer_runs = 1000000
remappings = ['openzeppelin/=lib/openzeppelin-contracts/contracts/', 'solmate/=lib/solmate/src/']

[profile.intense.fuzz]
runs = 10000

[fmt]
quote_style = 'single'
line_length = 90
